name: ci
on:
  push:
    branches: ['master', 'develop' ]
  pull_request:
    branches: ['master', 'develop']
    
workflow_dispatch

jobs:
  test:
    name: test
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: requirements install
        run:
          $GITHUB_WORKSPACE
      - name: run tests
        run: python3 -m unittest test_main.py
      
      
      
